# Default values for argo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

apps:
  kafka: {}
  kafka-manager: {}

global:
  project: default
  server: https://kubernetes.default.svc
  namespace: kafka

template:
  kafka-manager:
    source:
      repoURL: https://kubernetes-charts.storage.googleapis.com
      chart: kafka-manager
      targetRevision: 2.3.1
      helm:
        parameters:
          zkHosts: kafka-zookeeper:2181
          service.type: NodePort
          ingress.enabled: "true"
  kafka:
    source:
      repoURL: https://charts.bitnami.com/bitnami
      chart: kafka
      targetRevision: 11.2.0
      helm:
        parameters:
          service.type: NodePort
          service.nodePort: "30092"
          advertiseListeners: PLANETEXT://kafka:9092